password_file /home/mqtt-silno/silno-dom-server/mqtt_passwords
acl_file /home/mqtt-silno/silno-dom-server/mqtt_acl

listener 1883
allow_anonymous true

listener 9001
protocol websockets
allow_anonymous true
